//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.12 at 03:57:15 PM IST 
//


package com.ta.travelagency.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}token_id"/>
 *         &lt;element ref="{}user_role"/>
 *         &lt;element ref="{}user_level"/>
 *         &lt;element ref="{}agency_id"/>
 *         &lt;element ref="{}agent_id"/>
 *         &lt;element ref="{}branch_id"/>
 *         &lt;element ref="{}is_user_already_logged"/>
 *         &lt;element ref="{}is_access_limited"/>
 *         &lt;element ref="{}is_super_user"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tokenId",
    "userRole",
    "userLevel",
    "agencyId",
    "agentId",
    "branchId",
    "isMapApplicable",
    "isUserAlreadyLogged",
    "isAccessLimited",
    "isSuperUser"
})
@XmlRootElement(name = "ta_login_validation_rs")
public class TaLoginValidationRS {

    @XmlElement(name = "token_id", required = true)
    protected String tokenId;
    @XmlElement(name = "user_role", required = true)
    protected String userRole;
    @XmlElement(name = "user_level", required = true)
    protected String userLevel;
    @XmlElement(name = "agency_id", required = true)
    protected String agencyId;
    @XmlElement(name = "agent_id", required = true)
    protected String agentId; 
    @XmlElement(name = "branch_id", required = true)
    protected String branchId;  
    @XmlElement(name = "is_map_applicable", required = true)
    private String isMapApplicable;        
    @XmlElement(name = "is_user_already_logged", required = true)
    protected String isUserAlreadyLogged;
    @XmlElement(name = "is_access_limited", required = true)
    protected String isAccessLimited;
    @XmlElement(name = "is_super_user", required = true)
    protected String isSuperUser;

    /**
     * Gets the value of the tokenId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenId() {
        return tokenId;
    }

    /**
     * Sets the value of the tokenId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenId(String value) {
        this.tokenId = value;
    }

    /**
     * Gets the value of the userRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * Sets the value of the userRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserRole(String value) {
        this.userRole = value;
    }

    /**
     * Gets the value of the userLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserLevel() {
        return userLevel;
    }

    /**
     * Sets the value of the userLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserLevel(String value) {
        this.userLevel = value;
    }

    /**
     * Gets the value of the agencyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgencyId() {
        return agencyId;
    }

    /**
     * Sets the value of the agencyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgencyId(String value) {
        this.agencyId = value;
    }
    
    /**
     * Gets the value of the agentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */    
    public String getAgentId() {
        return agentId;
    }

    /**
     * Sets the value of the agentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */    
    public void setAgentId(String agentId) {
        this.agentId = agentId;
    }

    /**
     * Gets the value of the branchId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */       
    public String getBranchId() {
        return branchId;
    }

    /**
     * Sets the value of the branchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */       
    public void setBranchId(String branchId) {
        this.branchId = branchId;
    }    

    /**
     * Gets the value of the isUserAlreadyLogged property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsUserAlreadyLogged() {
        return isUserAlreadyLogged;
    }

    /**
     * Sets the value of the isUserAlreadyLogged property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsUserAlreadyLogged(String value) {
        this.isUserAlreadyLogged = value;
    }

    /**
     * Gets the value of the isAccessLimited property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsAccessLimited() {
        return isAccessLimited;
    }

    /**
     * Sets the value of the isAccessLimited property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsAccessLimited(String value) {
        this.isAccessLimited = value;
    }

    /**
     * Gets the value of the isSuperUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsSuperUser() {
        return isSuperUser;
    }

    /**
     * Sets the value of the isSuperUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsSuperUser(String value) {
        this.isSuperUser = value;
    }

    /**
     * @return the isMapApplicable
     */
    public String getIsMapApplicable() {
        return isMapApplicable;
    }

    /**
     * @param isMapApplicable the isMapApplicable to set
     */
    public void setIsMapApplicable(String isMapApplicable) {
        this.isMapApplicable = isMapApplicable;
    }
}
